# Generated by Django 4.1 on 2022-08-31 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(default='photos/no_image.png', upload_to='photos/%Y/%m/%d'),
        ),
    ]
